[workspace]
members = []
resolver = "3"

[workspace.package]
version = "0.1.0"
description = "Universal, decently fast, C ompiler (in Rust)"

[workspace.dependencies]
cgrammar = "0.9.1"

wasmparser = { version = "0.240.0", default-features = false }
wasm-encoder = { version = "0.240.0", default-features = false, features = [
    "wasmparser",
] }

wax-core = { version = "0.1.0", git = "https://github.com/portal-co/wax.git", branch = "main" }

portal-pc-asm-common = { version = "0.1.1", git = "https://github.com/portal-co/asm-common.git" }

portal-solutions-asm-x86-64 = {version = "0.1.0",git = "https://github.com/portal-co/asm-arch.git"}
portal-solutions-asm-riscv64 = {version = "0.1.0",git = "https://github.com/portal-co/asm-arch.git"}
portal-solutions-asm-aarch64 = {version = "0.1.0",git = "https://github.com/portal-co/asm-arch.git"}